services:

  mariadb:
    image: mariadb:12.3
    container_name: hospital-mariadb

    environment:
      MARIADB_DATABASE: SISHPTL
      MARIADB_USER: hospital_user
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    volumes:
      - mariadb_data:/var/lib/mysql

    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: hospital-backend

    environment:
      PORT: ${PORT}
      DB_DATASOURCE: ${DB_DATASOURCE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      TEXTBEE_API_KEY: ${TEXTBEE_API_KEY}

    depends_on:
      - mariadb

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: hospital-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped

volumes:
  mariadb_data: